"""initial migration

Revision ID: 6dad0ae1d6f4
Revises: 
Create Date: 2025-04-23 22:54:23.848206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6dad0ae1d6f4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_clients_api_key'), 'app_clients', ['api_key'], unique=True)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('gateway_ref', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('app_source', sa.String(), nullable=True),
    sa.Column('gateway', sa.Enum('STRIPE', 'FLUTTERWAVE', name='paymentgateway'), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('USD', 'NGN', name='paymentcurrency'), nullable=True),
    sa.Column('status', sa.Enum('PENDEING', 'SUCCESS', 'FAILED', 'CANCELED', name='paymentstatus'), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_app_source'), 'transactions', ['app_source'], unique=False)
    op.create_index(op.f('ix_transactions_email'), 'transactions', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_email'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_app_source'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_app_clients_api_key'), table_name='app_clients')
    op.drop_table('app_clients')
    # ### end Alembic commands ###
